steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node:latest
  args: ['npm', 'run']
  args: ['npm', 'build']
  args: ['echo', 'yo', 'node']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=anagaret --password=waM3GcWFYyUPwkX']
  args: ['-c', 'docker build -t anagaret/java-ci-cd .']
  args: ['-c', 'docker push anagaret/java-ci-cd']
